import crypto from "node:crypto";
const COOKIE_NAME="customs-idp-auth";
const MAX_AGE_SECONDS=60*15;
const DEFAULT_ORGANISATION_ID="demo-organisation";
function getSecret(){const configured=String(process.env.IDP_AUTH_SECRET||"").trim();if(!configured)throw new Error("IDP_AUTH_SECRET is required.");return configured;}
function sign(value){return crypto.createHmac("sha256",getSecret()).update(value).digest("base64url");}
function parseCookies(header=""){return Object.fromEntries(String(header).split(";").map(part=>part.trim()).filter(Boolean).map(part=>{const i=part.indexOf("=");return i<0?[part,""]:[part.slice(0,i),decodeURIComponent(part.slice(i+1))];}));}
export function createAuthCookie(context={},options={}){const payload=JSON.stringify({iat:Date.now(),organisationId:String(context.organisationId||DEFAULT_ORGANISATION_ID),userId:String(context.userId||""),email:String(context.email||""),name:String(context.name||""),role:String(context.role||"member")});const encoded=Buffer.from(payload).toString("base64url");const secure=options.secure===false?"":"; Secure";return COOKIE_NAME+"="+encodeURIComponent(encoded+"."+sign(encoded))+"; Path=/; HttpOnly"+secure+"; SameSite=Lax; Max-Age="+MAX_AGE_SECONDS;}
export function clearAuthCookie(){return COOKIE_NAME+"=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0";}
export function getAuthContext(req){const token=parseCookies(req.headers?.cookie||"")[COOKIE_NAME];if(!token)return null;const [encoded,signature]=String(token).split(".");if(!encoded||!signature)return null;let payload;try{payload=JSON.parse(Buffer.from(encoded,"base64url").toString("utf8"));}catch{return null;}const issuedAt=Number(payload?.iat),age=Date.now()-issuedAt;if(!Number.isFinite(issuedAt)||age<0||age>MAX_AGE_SECONDS*1000)return null;const expected=sign(encoded);if(signature.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return null;return {authenticated:true,organisationId:String(payload.organisationId||DEFAULT_ORGANISATION_ID),userId:String(payload.userId||""),email:String(payload.email||""),name:String(payload.name||""),role:String(payload.role||"member")};}
export function isAuthenticated(req){return Boolean(getAuthContext(req));}
export function requireAuth(req,res){let context=null;try{context=getAuthContext(req);}catch(error){res.status(503).json({error:error.message});return null;}if(context)return context;res.status(401).json({error:"Authentication required"});return null;}
